apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - image: ghcr.io/learnwithtwoheads/sample-projects/python-server:main-cdef060
        imagePullPolicy: IfNotPresent
        name: python-app
      imagePullSecrets:
      - name: twoheadsregistry
