apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
      - name: echoserver
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "8000"
